<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Personal Kanban Board</title>
    <link rel="stylesheet" href="/static/css/styles.css">
    <link rel="stylesheet" href="/static/css/kanban.css">
</head>
<body>
    <div class="container">
        <header>
            <h1>Personal Kanban Board</h1>
            <nav>
                <a href="/">Dashboard</a>
                <a href="/kanban" class="active">Kanban Board</a>
                <a href="/goals">My Goals</a>
                <a href="/data-transparency">Data Transparency</a>
                <a href="/settings">Settings</a>
            </nav>
        </header>

        <main>
            <div class="kanban-header">
                <h2>My Tasks</h2>
                <button id="add-task-btn" class="btn">Add New Task</button>
            </div>
            <div id="kanban-board" class="kanban-board">
                <!-- Columns and tasks will be dynamically generated by JavaScript -->
            </div>
        </main>
    </div>

    <!-- Add Task Modal -->
    <div id="add-task-modal" class="modal">
        <div class="modal-content">
            <span class="close-btn">&times;</span>
            <h2>Add a New Task</h2>
            <form id="add-task-form">
                <div class="form-group">
                    <label for="task-content">Task Description:</label>
                    <input type="text" id="task-content" name="task-content" required>
                </div>
                <button type="submit" class="btn">Add Task</button>
            </form>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/sortablejs@latest/Sortable.min.js"></script>
    <script src="/static/js/kanban.js"></script>
</body>
</html>